### ISSUE TITLE
Sweep (Fast): Add access log middleware

### ISSUE THREAD

**Issue by ofirdassa9** [ofirdassa9/ynd#1]
It should do the same as [morgan](https://github.com/expressjs/morgan) in expressjs

<details open>
<summary>Checklist</summary>

- [X] `services/accessLog.ts`
> • Create a new function named 'accessLogMiddleware' that takes in three parameters: 'req', 'res', and 'next'.
> • In this function, log the HTTP method, URL, and status code of the request. Use the 'req' parameter to access the method and URL, and the 'res' parameter to access the status code.
> • Call the 'next' function at the end of 'accessLogMiddleware' to ensure that the request is passed on to the next middleware function or route handler.

- [X] `server.ts`
> • Import the 'accessLogMiddleware' function from the newly created 'services/accessLog.ts' file.
> • Add 'accessLogMiddleware' to the 'plugins' array in the 'serve' function call. This will apply the middleware to all incoming requests.

</details>

**Comment by ofirdassa9** [comment]
This PR raises error:
http://localhost:8000/favicon.ico
TypeError: Cannot read properties of undefined (reading 'bodyUsed')
    at Server.#respond (https://deno.land/std@0.192.0/http/server.ts:301:20)
    at eventLoopTick (ext:core/01_core.js:183:11)
